apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: ollama
  annotations:
    scenarios.ai.sap.com/name: "ollama"
    scenarios.ai.sap.com/description: "Run a ollama server on SAP AI Core"
    executables.ai.sap.com/name: "ollama"
    executables.ai.sap.com/description: "ollama service"
  labels:
    scenarios.ai.sap.com/id: "ollama"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter  #WARINING: SAP AI Core, Free tier, allows only the Starter resource plan 
    spec: |
      predictor:
        imagePullSecrets:
        - name: credstutorialrepo #Your docker registry secret in SAP AI Core
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/phdaucourt/ollama:ai-core #Your docker image name
          ports:
            - containerPort: 8080
              protocol: TCP
